server.port=8081

spring.application.name=movie-service
spring.datasource.url=jdbc:postgresql://pg-2158b586-fullstackdeveloperns-d341.h.aivencloud.com:25350/defaultdb?sslmode=require
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
#spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.connection-timeout=30000

eureka.client.service-url.defaultZone = http://localhost:8761/eureka
