spring.application.name=theatre-service

server.port=8082

spring.datasource.url=jdbc:postgresql://db.lrowhawteursxdmtyyhp.supabase.co:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=Oscar@Babur0517

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

eureka.client.service-url.defaultZone = http://localhost:8761/eureka